### ISSUE TITLE
Unable to Build or serve on windows machine.

### ISSUE THREAD

**Issue by prashantsolanki3** [arkadianriver/arkadianriver.com#10]
Jekyll gives an error: `jekyll 3.1.2 | Error:  Permission denied - F:/..../Spectral-blog/css`.
I'm unable to find the solution on SO or Jekyll's official website.
Please help!

**Comment by arkadianriver** [comment]
Not in the original fork, right? Any new files in your css folder? what does `jekyll build --trace` show? Maybe push a branch and I'll take a look?

**Comment by prashantsolanki3** [comment]
It was the original fork, without any kind of change.
I don't know the reason for the error but It was solved by reinstalling both ruby and Jekyll.
Thank you for such a great theme.

**Comment by arkadianriver** [comment]
oh, cool, okay. Yeah, when I upgraded to jekyll 3.1.2 I also upgraded ruby to 2.1.8. Were you on ruby 2.0.0 before?

**Comment by prashantsolanki3** [comment]
No, I was on ruby 2.2.
I used chocolatey to install ruby only then I was able to get it working. Normal ruby installation was no good(for me).
