### ISSUE TITLE
Liquid Errors

### ISSUE THREAD

**Issue by sharpic** [arkadianriver/arkadianriver.com#15]
Hi, 
Thanks for this Theme - really enjoying it.

But for each post I'm getting

```
Liquid Warning: Liquid syntax error (line 23): Expected dotdot but found comparison in "sorted_list and (site.navlinks == 'top' or site.navlinks == 'both')" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 37): Expected dotdot but found comparison in "sorted_list and (site.navlinks == 'bottom' or site.navlinks == 'both')" in /_layouts/post.html
```

When I 'bundle exec jekyll serve' Doesn't seem to be hurting anything but not sure if it slowing the build down.

cheers
Si

**Comment by arkadianriver** [comment]
Sorry, just saw this. I didn't use bundler, but my jekyll version is 3.1.2. Am I outdated already? Add this to your Gemfile?
```
gem 'jekyll', '>= 3.1.2'
```

**Comment by arkadianriver** [comment]
Thanks for finding this @sharpic , fixed.
