### ISSUE TITLE
How to configure Google Analytics in the website?

### ISSUE THREAD

**Issue by palash-taneja** [arkadianriver/arkadianriver.com#16]

**Comment by arkadianriver** [comment]
For Disqus, after you register at http://disqus.com, add your shortname to your author entry in `_data\authors.yml`.

For Google Analytics, after you register at https://www.google.com/analytics/standard/ and create a property, add its Google Analytics tracking ID to `_data\tokens.yml`. (Use `_data\tokens-template.yml` as a guide.)

Hope that helps!
