### ISSUE TITLE
Make it easier to fit within a sub-directory

### ISSUE THREAD

**Issue by mgifford** [arkadianriver/arkadianriver.com#24]
I'd like to be able to put this in a sub-directory, but am having some difficulties.  Largely because I'm not quite sure what the code is doing.

You can see the repository here https://github.com/mgifford/wolford-or-gifsack

Basically I want to add in a password like https://github.com/matteobrusa/Password-protection-for-static-pages

Right now you have to put in the password "Ottawa" and it will direct you to a sub-directory.

https://mgifford.github.io/wolford-or-gifsack/

But then if I try to go to one of the pages within that I get a 404:
https://mgifford.github.io/wolford-or-gifsack/4df0179dda01538c9eedcafb8789c0805e4fd0c4/Vancouver/

The "Vancouver" directory doesn't exist (and it didn't before), but jekyll made it work earlier. 

Any ideas how to resolve this?

**Comment by arkadianriver** [comment]
Since you're only using pages and not posts, try moving the files in your `_pages` folder into that hash folder, and add `layout: page` to the top header.

**Comment by mgifford** [comment]
Thanks! I really don't understand how this config is being parsed.

I think I've done that now and am having the same effect 

This is how you were thinking it should look, right?
https://github.com/mgifford/wolford-or-gifsack/blob/master/4df0179dda01538c9eedcafb8789c0805e4fd0c4/_pages/ottawa.md

That's the layout: page reference.
