### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by fantasylion** [arkadianriver/arkadianriver.com#4]
Can you tell me how to use this code. I am pushed to my github page but it display 404

**Comment by arkadianriver** [comment]
Hi, @FantasyLions .. Looks like you got it working. You probably just needed to rename your repository FantasyLions.github.io. :O) Cheers

**Comment by fantasylion** [comment]
Thanks for your help! This problem caused by my domain have not CNAME to github page  -_-#

**Comment by arkadianriver** [comment]
Oh, I see.. you have another domain besides the github.io one. Yep.. good ol' DNS redirects are great. :O)
